# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # Sample build task
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd ./web
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run placeholder test
      # - run: npm test
  # Deploy with Surge task
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: cd ./web
      - run: surge --project ./dist
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
